server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;  # important for React Router
    }

    location /api {
        proxy_pass http://backend-service:8080;  # k8s service name
    }
}
